inherit_from: .rubocop_todo.yml
require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  NewCops: enable

Layout/LineLength:
  IgnoreCopDirectives: true
  Max: 107

Metrics/BlockLength:
  Exclude:
    - db/schema.rb

Metrics/MethodLength:
  Max: 24

Style/Documentation:
  Enabled: false
