inherit_from: .rubocop_todo.yml

Metrics/AbcSize:
  Max: 16

Metrics/BlockLength:
  Exclude:
    - db/schema.rb

Metrics/LineLength:
  IgnoreCopDirectives: true
  Max: 107

Metrics/MethodLength:
  Max: 24

Style/Documentation:
  Enabled: false
