#!/bin/bash
#
# front      Startup script for the KC front application
#
# chkconfig: 345 88 12
# description: KC front web application
# pidfile: /u/apps/$APP/shared/log/mongrel.pid

. /etc/rc.d/init.d/functions

APP=front
RUN_AS_USER=donv
PORT=3003
pidfile=${PIDFILE-/u/apps/$APP/shared/log/mongrel.pid}
APP_DIR="/u/apps/$APP/current"
LOG_DIR="/u/apps/$APP/shared/log"

USER=`whoami`

run() {
	cmd=$1
	if [ "$USER" != "$RUN_AS_USER" ]; then
		echo Running as $USER
        echo su - $RUN_AS_USER -c "$cmd"
        su - $RUN_AS_USER -c "$cmd"
    else
    	echo $cmd
        $cmd
    fi
}

# See how we were called.
case "$1" in
  start)
	if [ -f $pidfile ] && ! ps h `cat $pidfile` > /dev/null
	then
	    rm -f $pidfile
	fi
    run "mongrel_rails start -p $PORT -e production -c $APP_DIR -d 1>$LOG_DIR/stdout.log 2>$LOG_DIR/stderr.log"
    ;;
  stop)
    run "mongrel_rails stop -c $APP_DIR"
    ;;
  restart)
    run "mongrel_rails restart -c $APP_DIR"
    ;;
  status)
    ps -ef | grep $APP
    ;;
  *)
    echo $"Usage: $prog {start|stop|restart|status}"
    exit 1
esac

exit 0
